### ISSUE TITLE
PropertyDeclarationSniff bug?

### ISSUE THREAD

**Issue by bmitch** [bmitch/Codor#108]
See https://scrutinizer-ci.com/g/bmitch/churn-php/issues/master/files/src/Commands/ChurnCommand.php?orderField=path&order=asc&honorSelectedPaths=0

**Comment by eugenz3rr-arocom** [comment]
Can confirm. That there is a bug. But the link above is not working for me.

I'm using Drupal 9 with PHP 7.4 with bmitch/Codor version 1.2.2
Error thrown in `PropertyDeclarationSniff.php` » `handleError` » `Class contains undeclared property`

I tried to resolve the error by using this example https://github.com/bmitch/Codor#codorclassespropertydeclaration

The example does resolve the error that was thrown above but it is not the right way.
`public $myVariable;`

The right way would be to add variable to the class and the missing property's type declaration.  
`public MySpecialClass $myVariable;`

But when I try to do it the right way it throws an error 😭

**Comment by villfa** [comment]
Thank you @eugenz3rr-arocom for your report.

The next release ([1.2.3](https://github.com/bmitch/Codor/releases/tag/1.2.3)) will contain the correction of the problem you've described.
Please open another issue if you're still blocked.
