### ISSUE TITLE
Update `code_sniffer` version up to ^3.*

### ISSUE THREAD

**Issue by brutto** [bmitch/Codor#127]
Great sniffs but cannot use them inside my project via composer because use next versions of phpunit, phpcs etc. =\

**Comment by bmitch** [comment]
@brutto that is an excellent idea. I am very short on time lately but I do want to do this. If you are able to send a pull request that would be great, if not I will look into this once I have some time to. Thanks!

**Comment by brutto** [comment]
@bmitch Please link with #128 PR

**Comment by villfa** [comment]
Closed by #128.
This will be part of the 1.2.0 release.
