### ISSUE TITLE
Available for php8

### ISSUE THREAD

**Issue by kevin-schmitt** [bmitch/Codor#149]
Hello,

Codor work for php8 please? An update for new features?

Thanks

**Comment by villfa** [comment]
Hi,

Codor is compatible with PHP8 but it is not under active development.
If you need a new sniff open an issue to describe it or, even better, open a PR :)

Cheers,
Fabien

**Comment by kevin-schmitt** [comment]
Thanks,

I'm thinking of opening a PR and going back to open source, I just have to finish some projects for my job before.
:)

**Comment by bmitch** [comment]
Please feel free to open a PR @kevin-schmitt and if you need any help do not hesitate to ask!
