### ISSUE TITLE
Sniff to limit the use of `new`?

### ISSUE THREAD

**Issue by bmitch** [bmitch/Codor#25]
Instead of using `new` should be using DI. Should this be sniffed out?

**Comment by bmitch** [comment]
Maybe leave this as a warning and suggest using DI instead if applicable.

**Comment by kevin-schmitt** [comment]
Hello,

This issue is always ok? if yes i take please.

Thanks

**Comment by kevin-schmitt** [comment]
Hello,

Can you help me please ?
I try to register new sniff without success i have message 'sniff no registered'
In my test

```
<?php declare(strict_types = 1);

namespace Codor\Tests\Sniffs\Classes;

use Codor\Tests\BaseTestCase;

/** @group Classes */
class NewInstanceSniffTest extends BaseTestCase
{

    public function setup()
    {
        parent::setup();

        $this->runner->setSniff('Codor.Classes.NewInstance')->setFolder(__DIR__.'/Assets/NewInstanceSniff/');
    }

    /** @test */
    public function a_constructor_have_warning_if_use_new_class_in_constructor()
    {
        $results = $this->runner->sniff('NewInConstructor.inc');
        $this->assertSame(0, $results->getErrorCount());
        $this->assertSame(1, $results->getWarningCount());

    }
}
```


I created the sniff
![image](https://user-images.githubusercontent.com/10809414/150305720-af8229ea-5123-4b2b-bd4e-d3ff109c850e.png)

When i run the test
![image](https://user-images.githubusercontent.com/10809414/150306095-23636416-fc56-4b02-abe8-125c210c2921.png)

Thanks

**Comment by villfa** [comment]
I see there is a typo in the class name of the Sniff: `Intsance` instead of `Instance`.
Not sure if it will fix your issue though.

**Comment by kevin-schmitt** [comment]
Hello :) 

You can close this issue please ?

**Comment by villfa** [comment]
Closing since it's done in #153.
Thanks @kevin-schmitt
