### ISSUE TITLE
Remove any levels of indentation > 1

### ISSUE THREAD

**Issue by bmitch** [bmitch/Codor#40]
* https://github.com/bmitch/Codor/blob/c1447a29244d79fdf98313f5e61f5257a1913ce6/src/Codor/Sniffs/Files/IndentationLevelSniff.php#L59-L79

* https://github.com/bmitch/Codor/blob/c1447a29244d79fdf98313f5e61f5257a1913ce6/src/Codor/Sniffs/Files/ReturnNullSniff.php#L20-L48

Once fixed can remove the `@codingStandardsIgnoreStart` in the method doc block.

**Comment by winkbrace** [comment]
I think we can mark this solved ;)
