### ISSUE TITLE
Doesn't work with Atom Linter-PHPCS?

### ISSUE THREAD

**Issue by mikebronner** [bmitch/Codor#44]
I tried setting it up to use with Atom's Linter-Phpcs package, but PHPCS just stops running. I don't see any errors or warnings where I should. If I remove the custom config from the Linter-PHPCS configuration, it resumes working normally.

Any suggestions on what I might try to debug this?

Thanks! :)

**Comment by bmitch** [comment]
@mikebronner thanks for the report. I don't use Atom so I'm not familiar with the Linter-Phpcs. I will see if I can try it myself and duplicate the issue.

If you come across any more information that could help debug this would you mind passing it along? Thanks.

**Comment by bmitch** [comment]
Hey @mikebronner  I was able to get it to work in Atom 1.10.2 with linter-phpcs 1.5.3.

I created a fresh folder and did a `composer require bmitch/codor --dev`.

Then created a `src` folder within and a `Test.php` file within that.

Created a `codor.xml` file with the contents you'd see in the readme file.

Setup linter-phpcs to point to the `codor`.xml file:

![image](https://cloud.githubusercontent.com/assets/4009957/21120709/9c04a0fa-c0c0-11e6-93e1-2eae6ed5162d.png)

and if I violate one of the rules in the file it produces the error:

![image](https://cloud.githubusercontent.com/assets/4009957/21120750/c6c82ac8-c0c0-11e6-806f-69dd355b7ed0.png)

Hope that helps you get going.

**Comment by bmitch** [comment]
Closing this for now. Can re-open if you're still having issues.

**Comment by mikebronner** [comment]
Hi @bmitch, thanks for taking a look. I'm beginning to think it has to do with the linter-phpci package, as that is failing for me left and right, even without your package installed. I will update here if I find anything that indicates it might have to do with your package. :)

Thanks!
~Mike

**Comment by mikebronner** [comment]
@bmitch I wanted to follow up on this and let you know what happened. I reset everything and things seemed to work. Today I updated a few things, including the linter package, and am getting the following error:

```
Error: PHP Warning: Illegal string offset 'type' in /Users/mike/Developer/Sites/document-manager/vendor/bmitch/codor/src/Codor/Sniffs/Files/ReturnNullSniff.php on line 44 PHP Notice: Uninitialized string offset: 0 in /Users/mike/Developer/Sites/document-manager/vendor/bmitch/codor/src/Codor/Sniffs/Files/ReturnNullSniff.php on line 44
```

PHP 7.0
PHPCS 2.7.1
Codor 0.0.5

Thanks :)

**Comment by bmitch** [comment]
@mikebronner thanks, I'll re-open this and investigate.

**Comment by bmitch** [comment]
@mikebronner is it possible for you to paste the code that you have open in Atom when this error appears? I just tried duplicating it again but it all works as expected. Was thinking maybe your code has some edge case I haven't tested yet. Thanks.

**Comment by mikebronner** [comment]
@bmitch sorry for not responding. (I don't remember getting a notification, and of course it was the holidays, so much else going on.) If I do run into this again, I'll let you know.

**Comment by bmitch** [comment]
No problem @mikebronner. Thanks!
