### ISSUE TITLE
ignore try-catch block as indentation

### ISSUE THREAD

**Issue by winkbrace** [bmitch/Codor#45]
Currently any loop or conditional in a try-catch block is reported. The only workaround is to put it in a function, but that doesn't always make sense. It's basically doubling the amount of functions if you need a try-catch block.

```php
try {
    if ($this->eventShouldBeCollected($event)) {
        $this->collectEvent($event);
    }

    $this->fire($event);
} catch (\Exception) {
    // log event errors
}
```

also in the catch part:

```php
try {
    $this->response = $this->guzzle->request(...);
    // etc..
} catch (\GuzzleHttp\Exception\ClientException $e) {
    if ($e->getResponse()->getStatusCode() == 404) {
        throw VacancyIsClosed::forId($vacancyId);
    }
}
```

**Comment by bmitch** [comment]
Thanks @winkbrace. I can take a look at solving this unless you were interested in submitting a pull request?

**Comment by Itsupportharver** [comment]
Okay, good point. I'll give it a try this weekend.

**Comment by winkbrace** [comment]
Okay, good point. I'll give it a try this weekend.

**Comment by bmitch** [comment]
Hey @winkbrace I created a couple of tests for the indentation level sniff using your code snippets above and no errors or warnings were produced. So I was unable to duplicate the issue you are having.

I just committed these tests to the master branch. I'm going to close this for now but if you're still having the same issue can you please let me know? Maybe I'm missing a step in my attempt to duplicate.
