### ISSUE TITLE
Sniff to warn when extending a class.

### ISSUE THREAD

**Issue by bmitch** [bmitch/Codor#90]
The warning could suggest to use composition over inheritance.

@Exadra37 feel free to take this one if you wish :smiley:

**Comment by Exadra37** [comment]
I :heart:  this one, but I would like to see an option to make it required ;)

:+1:

**Comment by bmitch** [comment]
@Exadra37 I could look and see if that is something that can be configured. Would you mind opening a new issue for this request though? Thanks
